### ISSUE TITLE
SNMP TRAP causes panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Madpilot0** [soniah/gosnmp#244]
Hi,

I'm using Telegraf 1.14.5 which uses gosnmp 1.22 (I think Telegraf 1.15 will use 1.25)

Currently a specific SNMP TRAP causes a runtime error and forces a Telegraf restart.

https://github.com/influxdata/telegraf/issues/7340

```
panic: runtime error: index out of range [6] with length 6
goroutine 30 [running]:
github.com/soniah/gosnmp.parseLength(0xc0019be086, 0x6, 0xf7a, 0x10000000040e9a6, 0x0)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/helper.go:501 +0x8e
github.com/soniah/gosnmp.(*GoSNMP).decodeValue(0x44bdbe0, 0xc0019be086, 0x6, 0xf7a, 0x297de92, 0x5, 0x1, 0x0, 0xc00007cba8)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/helper.go:172 +0x1648
github.com/soniah/gosnmp.(*GoSNMP).decodeValue(0x44bdbe0, 0xc0019be084, 0x47, 0xf7c, 0x297de92, 0x5, 0xc001af4040, 0x1b, 0x0)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/helper.go:175 +0x16c4
github.com/soniah/gosnmp.(*GoSNMP).unmarshalVBL(0x44bdbe0, 0xc0019be01c, 0xaf, 0xfe4, 0xc001acfc00, 0x22e2940, 0x4639160)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/marshal.go:986 +0x377
github.com/soniah/gosnmp.(*GoSNMP).unmarshalResponse(0x44bdbe0, 0xc0019be00f, 0xbc, 0xff1, 0xc001acfc00, 0xe0, 0x2905360)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/marshal.go:871 +0x34e
github.com/soniah/gosnmp.(*GoSNMP).unmarshalPayload(0x44bdbe0, 0xc0019be000, 0xcb, 0x1000, 0xf, 0xc001acfc00, 0x0, 0x0)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/marshal.go:791 +0x9b
github.com/soniah/gosnmp.(*GoSNMP).UnmarshalTrap(0x44bdbe0, 0xc0019be000, 0xcb, 0x1000, 0xcb)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/trap.go:228 +0x31c
github.com/soniah/gosnmp.(*TrapListener).Listen(0xc000361ec0, 0x2989505, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/soniah/gosnmp@v1.22.0/trap.go:187 +0x2f9
github.com/influxdata/telegraf/plugins/inputs/snmp_trap.(*SnmpTrap).Start.func1(0xc00055c000, 0x2989505, 0x4)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/snmp_trap/snmp_trap.go:133 +0x43
created by github.com/influxdata/telegraf/plugins/inputs/snmp_trap.(*SnmpTrap).Start
	/go/src/github.com/influxdata/telegraf/plugins/inputs/snmp_trap/snmp_trap.go:132 +0x317
2020-07-08T06:30:30Z I! Starting Telegraf 1.14.5
```

I have a PCAP available with 3 packets causing this runtime error at [gdrive](https://drive.google.com/file/d/1bSobaQJGE3BJRJgr6Zng5tJLDoR6EnY8/view?usp=sharing)

I'm curious if this was fixed in one of the later releases (>=1.23) or if it is a brand new thing.

Thanks!

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by Madpilot0** [comment]
After updating Telegraf (and therefore gosnmp >= 1.29.0) we haven't encountered this issue anymore. Keeping an eye on the logs but feel free to close this issue.
