### ISSUE TITLE
Get() err: recover: crypto: requested hash function #3 is unavailable

### ISSUE THREAD

**Issue by licf327** [soniah/gosnmp#248]
example3               
go run snmp_example3.go 
2020/07/17 16:22:41 Get() err: recover: crypto: requested hash function #3 is unavailable
Stack:goroutine 1 [running]:
github.com/soniah/gosnmp.(*GoSNMP).send.func1(0xc000045d68)
	/root/go/src/github.com/soniah/gosnmp/marshal.go:320 +0xa1
panic(0x543f60, 0xc000012960)
	/usr/local/go/src/runtime/panic.go:969 +0x166
crypto.Hash.New(0x3, 0x1, 0xc000052300)
	/usr/local/go/src/crypto/crypto.go:89 +0x102
crypto/hmac.New(0xc000045a28, 0x0, 0x0, 0x0, 0xc00000e220, 0xc000045ae0)
	/usr/local/go/src/crypto/hmac/hmac.go:72 +0x45
github.com/soniah/gosnmp.(*UsmSecurityParameters).calcPacketDigest(0xc000070a90, 0xc00007c180, 0x75, 0x75, 0x0, 0x0, 0x5)
	/root/go/src/github.com/soniah/gosnmp/v3_usm.go:590 +0x1d6
github.com/soniah/gosnmp.(*UsmSecurityParameters).isAuthentic(0xc000070a90, 0xc00007c180, 0x75, 0x75, 0xc0000a42a0, 0x571740, 0x586480, 0xc000070c30)
	/root/go/src/github.com/soniah/gosnmp/v3_usm.go:628 +0x85
github.com/soniah/gosnmp.(*GoSNMP).testAuthentication(0xc00008e000, 0xc00007c180, 0x75, 0x75, 0xc0000a42a0, 0x3c, 0x0)
	/root/go/src/github.com/soniah/gosnmp/v3.go:96 +0x8e
github.com/soniah/gosnmp.(*GoSNMP).sendOneRequest(0xc00008e000, 0xc0000a40e0, 0x40de01, 0x10, 0x545b40, 0x7faa82d83101)
	/root/go/src/github.com/soniah/gosnmp/marshal.go:255 +0xbea
github.com/soniah/gosnmp.(*GoSNMP).negotiateInitialSecurityParameters(0xc00008e000, 0xc0000a4000, 0xc000045d00, 0x40de48)
	/root/go/src/github.com/soniah/gosnmp/v3.go:132 +0xe9
github.com/soniah/gosnmp.(*GoSNMP).send(0xc00008e000, 0xc0000a4000, 0xc00005c101, 0x0, 0x0, 0x0)
	/root/go/src/github.com/soniah/gosnmp/marshal.go:336 +0x7d9
github.com/soniah/gosnmp.(*GoSNMP).Get(0xc00008e000, 0xc000045ef8, 0x2, 0x2, 0x0, 0x1, 0xc00006e9f0)
	/root/go/src/github.com/soniah/gosnmp/gosnmp.go:365 +0x154
main.main()
	/usr/src/snmp_example3.go:35 +0x22b

exit status 1

code:
package main

import (
	"fmt"
	"log"

	g "github.com/soniah/gosnmp"
)

func main() {

	// build our own GoSNMP struct, rather than using g.Default
	params := &g.GoSNMP{
		Target:        "10.16.1.244",
		Port:          161,
		Version:       g.Version3,
                Timeout:       g.Default.Timeout,
		SecurityModel: g.UserSecurityModel,
		MsgFlags:      g.AuthPriv,
		SecurityParameters: &g.UsmSecurityParameters{
                        UserName: "authPrivCtt",
			AuthenticationProtocol:   g.SHA,
			AuthenticationPassphrase: "cttvoip555",
			PrivacyProtocol:          g.DES,
			PrivacyPassphrase:        "cttvoip555",
		},
	}
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer params.Conn.Close()

	oids := []string{".1.3.6.1.4.1.2021.4.5.0", ".1.3.6.1.4.1.2021.9.1.6.1"}
	result, err2 := params.Get(oids) // Get() accepts up to g.MAX_OIDS
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}

	for i, variable := range result.Variables {
		fmt.Printf("%d: oid: %s ", i, variable.Name)

		// the Value of each variable returned by Get() implements
		// interface{}. You could do a type switch...
		switch variable.Type {
			case g.OctetString:
				fmt.Printf("string: %s\n", string(variable.Value.([]byte)))
			default:
				// ... or often you're just interested in numeric values.
				// ToBigInt() will return the Value as a BigInt, for plugging
				// into your calculations.
				fmt.Printf("number: %d\n", g.ToBigInt(variable.Value))
		}
	}
}

snmpd server:net-snmp
 snmpd.service - LSB: SNMP agents
   Loaded: loaded (/etc/init.d/snmpd)
   Active: active (running) since Fri 2020-07-17 16:13:40 HKT; 20min ago
  Process: 55230 ExecStop=/etc/init.d/snmpd stop (code=exited, status=0/SUCCESS)
  Process: 55235 ExecStart=/etc/init.d/snmpd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/snmpd.service
           └─55241 /usr/sbin/snmpd -Lsd -Lf /dev/null -u snmp -g snmp -I -smux mteTrigger mteTriggerConf -p /run/snmpd.pid

Jul 17 16:20:20 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:39114->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:33000->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:33000->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:33000->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:47990->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:47990->[10.16.1.244]:161
Jul 17 16:20:21 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:47990->[10.16.1.244]:161
Jul 17 16:22:41 licf snmpd[55241]: Connection from UDP: [10.16.1.211]:53383->[10.16.1.244]:161
Jul 17 16:30:24 licf snmpd[55241]: Connection from UDP: [10.16.1.29]:35236->[10.16.255.255]:161
Jul 17 16:30:24 licf snmpd[55241]: Connection from UDP: [10.16.1.29]:35236->[10.16.255.255]:161

**Comment by licf327** [comment]
I have checkout v1.25.0, which is ok!
