### ISSUE TITLE
V3 Index out of range

### ISSUE THREAD

**Issue by Setheck** [soniah/gosnmp#250]
I'm seeing the following panic,

```
error: recover: runtime error: slice bounds out of range [:-9061804296214805629]

Stack:goroutine 48 [running]:
github.com/soniah/gosnmp.(*GoSNMP).send.func1(0xc00030f9b0)
    /Users/username/go/pkg/mod/github.com/soniah/gosnmp@v1.27.0/marshal.go:320 +0xa1
panic(0xa207c0, 0xc0004b1b00)
    /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/soniah/gosnmp.(*GoSNMP).decryptPacket(0xc0003527e0, 0xc0001c4120, 0x88, 0x8a, 0x50, 0xc000649340, 0x0, 0x0, 0x414157, 0x7f1e5af67068, ...)
    /Users/username/go/pkg/mod/github.com/soniah/gosnmp@v1.27.0/v3.go:437 +0xaa4
github.com/soniah/gosnmp.(*GoSNMP).sendOneRequest(0xc0003527e0, 0xc000649180, 0x1, 0x0, 0xe0, 0xa420c0)
    /Users/username/go/pkg/mod/github.com/soniah/gosnmp@v1.27.0/marshal.go:260 +0xc4b
github.com/soniah/gosnmp.(*GoSNMP).send(0xc0003527e0, 0xc000649180, 0xc000395101, 0x0, 0x0, 0x0)
    /Users/username/go/pkg/mod/github.com/soniah/gosnmp@v1.27.0/marshal.go:343 +0xef
github.com/soniah/gosnmp.(*GoSNMP).Get(0xc0003527e0, 0xc0004b4b70, 0x1, 0x1, 0x22, 0x80, 0x98b4e0)
    /Users/username/go/pkg/mod/github.com/soniah/gosnmp@v1.27.0/gosnmp.go:365 +0x154
```

line v3.go 437 is
```
packet = packet[:cursor+tlength]
```
which makes it seem like the `parseLength(packet[cursor:])` calculation is incorrect?

**Comment by soniah** [comment]
Please see my comment in README:

11 July 2020 - I'm planning on archiving gosnmp, as maintaining it is having too much of an effect on my work and personal life. I started the fork in March 2013 and I've been working on it ever since.

At the moment I'm keeping it open so it can act as a central clearing house for issues and discussions around who is going to fork and maintain gosnmp.

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by rahul-vunet** [comment]
Any updates on this?

**Comment by Setheck** [comment]
> I am facing the same issue. Any workaround for this issue?

I was unable to find a real workaround. Although I did add a simple retry in my app and that mitigated the issue. I found that this never seems to occur twice in a row.

**Comment by TomSellers** [comment]
Note that this may be fixed by PR #443. There were two issues there that might be related:
- `UsmSecurityParameters.decryptPacket()` was trying to decrypt by default, even when `sp.PrivacyProtocol` was `NoPriv` and so `sp.PrivacyKey` was an empty slice.
- A integer overflow bug in `parseLength` could result in `length` being less than `cursor`. That being said, in the panic in the original comment `tlength` was negative which I think has been fixed already.
