### ISSUE TITLE
parseRawField is panic

### ISSUE THREAD

**Issue by runner-mei** [soniah/gosnmp#252]
````
goroutine 1 [running]:
github.com/soniah/gosnmp.parseRawField(0x0, 0x0, 0xc00021e003, 0x8e, 0xffd, 0xda867a, 0x7, 0x0, 0xc0005b2300, 0x2030000, ...)
	d:/developing/go/meijing/tpt_vendor/src/github.com/soniah/gosnmp/helper.go:628 +0x17d
github.com/soniah/gosnmp.(*GoSNMP).unmarshalHeader(0xc0001985a0, 0xc00021e000, 0x91, 0x1000, 0xc0001400e0, 0x0, 0xc000487c00, 0x5)
	d:/developing/go/meijing/tpt_vendor/src/github.com/soniah/gosnmp/marshal.go:822 +0x3e4
github.com/soniah/gosnmp.(*GoSNMP).UnmarshalTrap(0xc0001985a0, 0xc00021e000, 0x91, 0x1000, 0x0)
	d:/developing/go/meijing/tpt_vendor/src/github.com/soniah/gosnmp/trap.go:376 +0xa7
cn/com/hengwei/pkg/tools/snmp.(*Unmarshaler).UnmarshalTrap(0xc0000a0140, 0xef5800, 0xc000135c20, 0xc00021e000, 0x91, 0x1000, 0xc00021e000)
	d:/developing/go/meijing/src/cn/com/hengwei/pkg/tools/snmp/unmarshaler.go:119 +0x132
cn/com/hengwei/pkg/tools/snmp.(*TrapListener).unmarshalTrap(...)
````

**Comment by soniah** [comment]
Please see README - `11 July 2020 - I'm planning on archiving gosnmp, as maintaining it is having too much of an effect on my work and personal life. I started the fork in March 2013 and I've been working on it ever since.`
